language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.36.0
  - 1.37.0
  - 1.38.0
  - 1.39.0
  - 1.40.0
  - 1.41.0

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
