language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.13.0
  - 1.15.0
  - 1.19.0
  - 1.20.0
  - 1.21.0
  - 1.25.0
  - 1.26.0
  - 1.28.0
  - 1.34.0
  - 1.36.0
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
