[package]
name = "serde-meta"
version = "0.1.0"
authors = ["Thomas Lahmer <791550+Tomok@users.noreply.github.com>"]
edition = "2018"

[dependencies]
proc-macro2 = { version = "0.4.30" }
serde = { version = "1.0"}

[dev-dependencies]
serde_json = "1.0"